### ISSUE TITLE
Set default layouts

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-theme-legumeinfo#56]
The theme provides a lot of layouts but none of them are being used by default, other than the "default.html" layout that is automatically used by Jekyll. Update the `_config.yml` file to assign as many default layouts as possible. For example:
```yml
defaults:
  -
    scope:
      path: "blog/" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "blog-item"
```
